### ISSUE TITLE
Double-agentname in message box

### ISSUE THREAD

**Issue by mxxcon** [hansolo669/iitc-tweaks#25]
Once I enable chat-toolbox plugin and add `xmps\.biz|ingressfarm\.com|ingress-shop\.net|allforingress\.ecwid\.com|shop-ingress\.com|ingintems\.net` block filter (spam) If I click on somebody's agent name in comm, it shows up twice in the message box

In this screenshot I clicked on GreedySalmon only once

![chat](https://cloud.githubusercontent.com/assets/847140/21558796/c1344a88-ce0d-11e6-90c8-1915db894531.png)

With this plugin disabled everything works as intended.

**Comment by cal-smith** [comment]
Thanks for doing the digging on this! I'll admit I've noticed it but never quite investigated - I think the fix should be relatively simple (double event binding due to overriding a bunch of the render code).
