### ISSUE TITLE
chat-tools has a huge performance hotspot in match_filter/match_highlight

### ISSUE THREAD

**Issue by nhamer** [hansolo669/iitc-tweaks#28]
If a chat window has any significant amount of messages in it, updates become extremely slow.

Calls to window.chat.getActive() dominate the profile graph - it's called for each message, for each filter defined.

Should be queried once in the overridden window.chat.renderData() and passed to match-filter/match_highlight

**Comment by cal-smith** [comment]
v0.1.3 has a whole bunch of performance improvements, mainly due to factoring out jquery code ... just pushed the update.
